## ubuntu-common

---
- name: Update apt package repository
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: yes

- name: Check to see if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_installed

- name: Install dependencies
  apt:
    name:
      - curl
      - ca-certificates
      - dnsutils
      - iputils-ping
      - ufw
      - lsof
      - chrony
      - nmap
      - figlet
    state: present
    update_cache: yes

- name: Allow ssh port in ufw
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Enable ufw
  ufw:
    state: enabled

- name: Download official docker install script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
  register: docker_script_downloaded
  when: not docker_installed.stat.exists

- name: Run docker install script
  command: |
    bash /tmp/get-docker.sh
  args:
    creates: /usr/bin/docker
  when: not docker_installed.stat.exists

- name: Cleanup docker install script if docker installed successfully
  file:
    path: /tmp/get-docker.sh
    state: absent

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Ensure all changes are flushed to disk
  shell: sync

- name: Reboot to apply group and path changes
  reboot:
    reboot_timeout: 300
  when: docker_script_downloaded is defined and docker_script_downloaded.changed

- name: Wait for system to come back online
  wait_for_connection:
    timeout: 300

- name: Comment out existing chrony NTP sources
  ansible.builtin.replace:
    path: /etc/chrony/chrony.conf
    regexp: '^(?!#)(pool|server|sourcedir)\s+.*'
    replace: '# \g<0>'

- name: Add custom NTP servers
  ansible.builtin.blockinfile:
    path: /etc/chrony/chrony.conf
    marker: "# {mark} ANSIBLE MANAGED NTP SOURCES"
    block: |
      server raspi iburst

- name: Restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted

- name: Rename existing motd scripts
  ansible.builtin.command:
    cmd: mv /etc/update-motd.d /etc/update-motd.d-backup
  args:
    creates: /etc/update-motd.d-backup

- name: Copy my motd.sh scipt to profile
  copy:
    src: motd.sh
    dest: /etc/profile.d/motd.sh
    owner: root
    group: root
    mode: "0755"

- name: Copy sshd config to pam.d
  copy:
    src: sshd
    dest: /etc/pam.d/sshd
    owner: root
    group: root
    mode: "0644"

- name: Copy sshd_config to /etc/ssh
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"

- name: Restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted