---
- name: setup arch-main
  hosts: arch-main
  roles:
    - { role: arch_network_setup, become: true }
    - { role: arch_grub_setup, become: true }
    - { role: arch_install_packages, become: true }
    - { role: arch_copy_config_files }
    - { role: arch_post_install_setup , become: true }

- name: Setup dns servers
  hosts: dns_servers
  roles:
    - { role: dns_setup, become: true }

- name: Setup NTP server
  hosts: raspi
  roles:
    - { role: setup_ntp_server, become: true }

- name: Setup apt-repo
  hosts: dns-node2
  roles:
  - { role: setup_apt_repo, become: true }

- name: Setup ubuntu-servers
  hosts: ubuntu_servers
  roles:
    - { role: ubuntu_common , become: true }

- name: Setup nginx reverse proxy
  hosts: raspi
  roles:
    - { role: setup_nginx_rp, become: true }

- name: Setup qnetd voter
  hosts: raspi
  roles:
    - { role: setup_qnetd, become: true }

- name: Setup nas 
  hosts: nas
  roles:
    - { role: setup_nas, become: true }

- name: Setup K8s common
  hosts: k8s_cluster
  roles:
    - { role: k8s_common, become: true }

- name: Initialize K8s control plane
  hosts: k8s_master
  roles:
    - { role: k8s_control_plane, become: true }

- name: Join K8s workers
  hosts: k8s_workers
  serial: 1
  roles:
    - { role: k8s_worker, become: true }
