---
all:
  hosts:
    arch-main:
      ansible_connection: local
      ansible_user: shaan
    arch-server1:
      ansible_connection: 10.25.100.20
      ansible_user: shaan
#    arch-server2:  
#      ansible_connection: 10.25.100.21
#      ansible_user: shaan

  children:
    arch-main:
      hosts:
        arch-main:
    arch-servers:
      hosts:
        arch-server1:
#        arch-server2:
