---
all:
  hosts:
    arch-main:
      ansible_user: shaan
      ansible_host: arch-main
      ansible_connection: local

    raspi:
      ansible_host: raspi
      ansible_user: shaan

    k8s-master:
      ansible_host: k8s-master
      ansible_user: shaan
      
    k8s-node1:
      ansible_host: k8s-node1
      ansible_user: shaan

    # k8s-node2:
    #   ansible_host: k8s-node2
    #   ansible_user: shaan

    nas:
      ansible_host: nas
      ansible_user: shaan

    # nas-node2:
    #   ansible_host: nas-node2
    #   ansible_user: shaan

    # pve-node2:
    #   ansible_host: pve-node2
    #   ansible_user: root

    pve-node1:
      ansible_host: pve-node1
      ansible_user: root

    pbs:
      ansible_host: pbs
      ansible_user: root

  children:
    debian_servers:
      hosts:
        raspi:
        k8s-master:  ## same as raspi
        k8s-node1:
        # k8s-node2:
        nas:
        # nas-node2:
        
    dns_servers:
      hosts:
        raspi:

    k8s_cluster:
      hosts:
        k8s-master:
        k8s-node1:
        # k8s-node2:

    k8s_master:
      hosts:
        k8s-master:

    k8s_workers:
      hosts:
        k8s-node1:
        # k8s-node2:
    
    proxmox:
      hosts:
        pve-node1:
        # pve-node2:
        pbs:
