---
all:
  hosts:
    arch-main:
      ansible_connection: local
      ansible_user: shaan
      ansible_host: arch-main.home.shaansomaiah.com

    dns-node1:
      ansible_host: dns-node1
      ansible_user: shaan

    dns-node2:
      ansible_host: dns-node2
      ansible_user: shaan

    k8s-master:
      ansible_host: k8s-master
      ansible_user: shaan
      
    k8s-node1:
      ansible_host: k8s-node1
      ansible_user: shaan

    k8s-node2:
      ansible_host: k8s-node2
      ansible_user: shaan

    k8s-node3:
      ansible_host: k8s-node3
      ansible_user: shaan

    jenkins:
      ansible_host: jenkins
      ansible_user: shaan

  children:
    ubuntu-servers:
      hosts:
        dns-node1:
        dns-node2:
        k8s-master:
        k8s-node1:
        k8s-node2:
        k8s-node3:
        jenkins:
        
    dns_servers:
      hosts:
        dns-node1:
        dns-node2:

    k8s-master:
      hosts:
        k8s-master:

    k8s-workers:
      hosts:
        k8s-node1:
        k8s-node2:
        k8s-node3:


