## Setup nginx as reverse proxy and generate trusted Let's Encrypt ssl certificate

- name: Create nginx directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ nginx_base_dir }}"
    - "{{ nginx_base_dir }}/certs"
    - "{{ nginx_base_dir }}/conf.d"
    - "{{ nginx_base_dir }}/scripts"

- name: Deploy nginx.conf
  copy:
    src: nginx.conf
    dest: "{{ nginx_base_dir }}/nginx.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Deploy compose file
  copy:
    src: docker-compose.yml
    dest: "{{ nginx_base_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Deploy proxy configs
  copy:
    src: conf.d/
    dest: "{{ nginx_base_dir }}/conf.d/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Start nginx container
  community.docker.docker_compose_v2:
    project_src: "{{ nginx_base_dir }}"

- name: Check acme.sh installation
  stat:
    path: "/home/{{ ansible_user }}/.acme.sh/acme.sh"
  register: acme_installed

- name: Wait for DNS resolution
  ansible.builtin.command:
    cmd: nslookup {{ item }}
  register: dns_lookup
  changed_when: false
  retries: 10
  delay: 5
  until: dns_lookup.rc == 0
  loop:
    - "get.acme.sh"

- name: Install acme.sh if not already installed
  shell: curl https://get.acme.sh | sh
  become_user: "{{ ansible_user }}"
  when: not acme_installed.stat.exists

- name: Check acme managed certificates for {{ wildcard_domain }}
  shell: ~/.acme.sh/acme.sh --list
  become_user: "{{ ansible_user }}"
  register: acme_list
  changed_when: false

- name: Issue wildcard certificate for {{ wildcard_domain }} if not already issued
  shell: |
    export CF_Token="{{ cloudflare_api_token }}"

    ~/.acme.sh/acme.sh \
      --issue \
      --server letsencrypt \
      --dns dns_cf \
      -d "{{ wildcard_domain }}"
  args:
    executable: /bin/bash
  become_user: "{{ ansible_user }}"
  when: wildcard_domain not in acme_list.stdout

- name: Install certificate into {{ nginx_base_dir }}/certs
  shell: |
    ~/.acme.sh/acme.sh \
      --install-cert \
      -d "{{ wildcard_domain }}" \
      --key-file {{ nginx_base_dir }}/certs/privkey.pem \
      --fullchain-file {{ nginx_base_dir }}/certs/fullchain.pem
##       --reloadcmd "docker exec nginx-proxy nginx -s reload"
  become_user: "{{ ansible_user }}"

- name: Verify certificate files exist under {{ nginx_base_dir }}/certs
  stat:
    path: "{{ item }}"
  register: cert_files
  loop:
    - "{{ nginx_base_dir }}/certs/fullchain.pem"
    - "{{ nginx_base_dir }}/certs/privkey.pem"

- name: Fail if certificate files missing
  fail:
    msg: "Certificate installation failed"
  when: not item.stat.exists
  loop: "{{ cert_files.results }}"
