## Play to setup dns server on ubuntu server
## Uses pihole + bind9 within docker containers
---

- name: Modify /etc/resolv.conf with fallback and localdns
  copy:
    dest: /etc/resolv.conf
    content: |
      search {{ SEARCH_DOMAIN }}
      nameserver {{ DNS_1 }}
      nameserver {{ DNS_2 }}

- name: Update apt package repository
  apt:
    update_cache: yes

- name: Check to see if nerdctl is installed
  stat:
    path: /usr/bin/nerdctl
  register: nerdctl_installed

- name: Install dependencies
  apt:
    name:
      - containerd
      - containernetworking-plugins
      - curl
      - ca-certificates
      - dnsutils
      - iputils-ping
      - ufw
      - lsof
      - chrony
      - nmap
      - figlet
    state: present
    update_cache: yes

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: true
    state: started

- name: Download nerdctl minimal
  get_url:
    url: https://github.com/containerd/nerdctl/releases/download/v2.3.5/nerdctl-2.3.5-linux-arm64.tar.gz
    dest: /tmp/nerdctl-2.3.5-linux-amd64.tar.gz
    mode: '0755'
  register: nerdctl_downloaded
  when: not nerdctl_installed.stat.exists

- name: Install nerdctl minimal
  command: tar -C /usr/bin -xzf /tmp/nerdctl-2.3.5-linux-amd64.tar.gz
  when: nerdctl_downloaded.changed

- name: Allow DNS to host
  ufw:
    rule: allow
    port: 53
    proto: "{{ item }}"
  loop:
    - tcp
    - udp

- name: Allow forwarded DNS to containers
  ufw:
    rule: allow
    route: yes
    to_ip: 172.25.100.0/24
    port: "53"
    proto: "{{ item }}"
  loop:
    - udp
    - tcp

- name: Allow ssh
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Enable ufw
  ufw:
    state: enabled

- name: Gather service facts
  service_facts:

- name: Stop services that may take up port 53
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - systemd-resolved.service
    - avahi-daemon.socket
    - avahi-daemon.service
  when: item in ansible_facts.services

- name: Copy docker compose and config files to /home/{{ ansible_user }}
  copy:
    src: dns/
    dest: /home/{{ ansible_user }}/dns/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Set permission recursive for files
  file:
    path: /home/{{ ansible_user }}/dns
    recurse: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Set permission recursive for directories
  file:
    path: /home/{{ ansible_user }}/dns
    recurse: yes
    state: directory
    mode: '0755'

- name: Start containers using docker compose
  command: |
    nerdctl compose up -d
  args:
    chdir: /home/{{ ansible_user }}/dns

- name: Wait for 20s for container to come up
  wait_for:
    timeout: 20

- name: Test if dns is working as expected
  command: |
    nslookup google.com 127.0.0.1
  register: dns_working
  ignore_errors: true

- name: Modify /etc/resolv.conf to remove fallbackdns
  copy:
    dest: /etc/resolv.conf
    content: |
      search {{ SEARCH_DOMAIN }}
      nameserver {{ DNS_1 }}
  when: dns_working is defined and dns_working.rc == 0

- name: Add cron to restart dns
  ansible.builtin.cron:
    name: "Daily dns restart"
    minute: "0"
    hour: "6"
    user: "{{ ansible_user }}"
    job: "/usr/bin/nerdctl compose -f /home/{{ ansible_user }}/dns/docker-compose.yml down && /usr/bin/nerdctl compose -f /home/{{ ansible_user }}/dns/docker-compose.yml up -d"
