---
  ## To rerun pass clean=true as extra argument when running ansible playbook

  - name: Create dir for system connections
    ansible.builtin.file:
      path: /etc/NetworkManager/system-connections
      state: directory
      recurse: yes
      mode: '0755'
  
  - name: Copy eth0 config file
    copy:
      src: eth0.nmconnection
      dest: /etc/NetworkManager/system-connections/eth0.nmconnection
      owner: "root"
      group: "root"
      mode: '0600'

  - name: Copy eth0.30 config file
    copy:
      src: eth0.30.nmconnection
      dest: /etc/NetworkManager/system-connections/eth0.30.nmconnection
      owner: "root"
      group: "root"
      mode: '0600'

  - name: Reload NetworkManager connection profiles
    ansible.builtin.command:
      cmd: nmcli connection reload

  - name: Activate VLAN 30
    ansible.builtin.command:
      cmd: nmcli connection up eth0.30

