---
- name: Install dependencies
  apt:
    name:
      - apt-cacher-ng
      - ufw
    state: present
    update_cache: yes

- name: Allow tcp port 3142 in ufw for apt-cacher-ng
  ufw:
    rule: allow
    port: 3142
    proto: tcp

- name: Allow ssh port in ufw
  ufw:
    rule: allow
    port: 22
    proto: tcp
