---
  my_packages:
    - woff2-font-awesome
    - ttf-jetbrains-mono-nerd
    - ttf-fira-sans
    - thunar
    - firefox
    - make
    - cmake
    - unzip
    - fd
    - snapper
    - fastfetch
    - wayland
    - hyprland
    - ripgrep
    - ufw
    - kitty
    - rsync
    - git
    - openssh
    - cronie
    - bluez
    - bluez-utils
    - waybar
    - hyprlock
    - hypridle
    - hyprpaper
    - qemu
    - libvirt
    - rofi
    - papirus-icon-theme
    - btop
    - nfs-utils
    - man
    - neovim
    - gcc
    - gdb
    - bash-completion
    - base-devel
    - inotify-tools
    - swaync
    - otf-codenewroman-nerd
    - dnsmasq
    - hyprpicker
    - python-pywal
    - blueman
    - gvfs
    - nmap
    - wl-clipboard
    - dnsutils
    - net-tools
    - wireshark-qt
    - wireshark-cli
    - tcpdump
    - hyprpolkitagent
    - tmux
    - dnsutils
    - chrony
    - kubectl
    - google-glog
    - gflags
    - protobuf
    - grpc
    - ninja
    - meson
    - noto-fonts
    - noto-fonts-cjk
    - ttf-dejavu
    - noto-fonts-emoji
    - nvidia-open-lts
    - nvidia-utils
    - lib32-nvidia-utils
    - steam
    - vulkan-tools
    - mesa-utils
    - gamemode
    - mangohud
    - gamescope
    - protontricks
    - nwg-look
    - adw-gtk-theme
    - iperf3
