---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - zfsutils-linux
      - nfs-kernel-server
      - gpg
      - rclone
      - smartmontools
      - nvme-cli
      - jq
      - curl
      - git
    state: present
    update_cache: true

- name: Verify ZFS pool exists
  ansible.builtin.command:
    cmd: zpool list {{ zfs_pool }}
  changed_when: false

- name: Configure ZFS cachefile
  ansible.builtin.command:
    cmd: zpool set cachefile=/etc/zfs/zpool.cache {{ zfs_pool }}
  changed_when: false

- name: Enabled installed services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - nfs-server
    - zfs-import-cache.service
    - zfs-mount.service
    - zfs-zed.service

- name: Enable lz4 compression
  ansible.builtin.command:
    cmd: zfs set compression=lz4 {{ zfs_pool }}
  changed_when: false

- name: Disable atime
  ansible.builtin.command:
    cmd: zfs set atime=off {{ zfs_pool }}
  changed_when: false

- name: Store xattrs efficiently
  ansible.builtin.command:
    cmd: zfs set xattr=sa {{ zfs_pool }}
  changed_when: false

- name: Enable autoexpand
  ansible.builtin.command:
    cmd: zpool set autoexpand=on {{ zfs_pool }}
  changed_when: false

- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download Kopia GPG key
  ansible.builtin.get_url:
    url: https://kopia.io/signing-key
    dest: /tmp/kopia-signing-key
    mode: "0644"
  register: kopia_key

- name: Install Kopia GPG key
  ansible.builtin.command:
    cmd: >
      gpg --dearmor
      --yes
      --output /etc/apt/keyrings/kopia-keyring.gpg
      /tmp/kopia-signing-key
  when: kopia_key.changed

- name: Configure Kopia repository
  ansible.builtin.deb822_repository:
    name: kopia
    types:
      - deb
    uris: http://packages.kopia.io/apt/
    suites: stable
    components:
      - main
    signed_by: /etc/apt/keyrings/kopia-keyring.gpg
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Kopia
  ansible.builtin.apt:
    name: kopia
    state: present

- name: Remove temporary Kopia GPG key
  ansible.builtin.file:
    path: /tmp/kopia-signing-key
    state: absent

- name: Create root config directory
  ansible.builtin.file:
    path: /root/.config/
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create rclone config directory
  ansible.builtin.file:
    path: /root/.config/rclone
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create Kopia config directory
  ansible.builtin.file:
    path: /root/.config/kopia
    state: directory
    owner: "root"
    group: "root"
    mode: "0700"

# - name: Install rclone configuration
#   ansible.builtin.copy:
#     src: rclone.conf
#     dest: /root/.config/rclone/rclone.conf
#     owner: "root"
#     group: "root"
#     mode: "0600"

- name: Install Kopia repository configuration
  ansible.builtin.copy:
    src: repository.config
    dest: /root/.config/kopia/repository.config
    owner: "root"
    group: "root"
    mode: "0600"

- name: Install Kopia repository password
  ansible.builtin.copy:
    src: repository.config.kopia-password
    dest: /root/.config/kopia/repository.config.kopia-password
    owner: "root"
    group: "root"
    mode: "0600"

- name: List Kopia snapshots
  ansible.builtin.command:
    cmd: kopia snapshot list
  register: kopia_snapshots
  changed_when: false

- name: Display snapshot status
  ansible.builtin.debug:
    var: kopia_snapshots.stdout_lines
